

spring:
  application:
    name: video

  datasource:
    url: jdbc:postgresql://198.74.53.107:5432/videoapi
    username: lk
    password: password_lk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
